name: Deploy to AWS EC2 instance

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    #- name: Configure AWS credentials
    #  uses: aws-actions/configure-aws-credentials@v1.7.0
    #  with:
    #    role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
    #    role-session-name: ${{ secrets.ROLE_SESSION_NAME }}
    #    aws-region: ${{ secrets.AWS_REGION }}

    - name: Connect to EC2 instance and run deployment script
      env:
        AWS_EC2_KEY: ${{ secrets.AWS_EC2_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$AWS_EC2_KEY" > ~/.ssh/private_key
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/private_key
        chmod 755 ~
        ssh -o "StrictHostKeyChecking=no" -i ~/.ssh/private_key ec2-user@54.74.104.12 "bash /var/www/deployment.sh"
